name: sensor_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  camera: ^0.10.4
  flutter:
    sdk: flutter
  flutter_masked_text: ^0.8.0
  flutter_sensors: ^1.0.1
  syncfusion_flutter_charts: ^21.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
